name: Data Pipeline

"on":
  workflow_dispatch:
  # schedule:
  #  # * is a special character in YAML so you have to quote this string
  #  - cron: "30 23 * * *"

# Cancel any in-flight jobs
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pipenv

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: pipenv sync

      - name: Install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          cpanfile: cpanfile

      - name: Run DVC pipelines
        run: |
          pipenv run dvc update -R raw-data
          pipenv run dvc repro -R pipelines

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data updates
          file_pattern: raw-data pipelines src/_data/sources
